# Generated by Selenium IDE
import pytest
import time
import json
import random
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test:
    def setup_method(self):
        options = Options()
        options.add_experimental_option("detach", True)
        options.add_argument('--ignore-ssl-errors=yes')
        options.add_argument('--ignore-certificate-errors')
        options.add_argument('--allow-insecure-localhost')
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test(self):
        self.driver.get("https://prestashop:8443/index.php")
        self.driver.maximize_window()
        #### TEST 1 ####
        element = self.driver.find_element(By.CSS_SELECTOR, "#category-211 > .dropdown-item")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Torby do laptopów").click()
        self.driver.find_element(By.CSS_SELECTOR, ".thumbnail > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".touchspin-up").click()
        self.driver.find_element(By.CSS_SELECTOR, ".touchspin-up").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        self.driver.implicitly_wait(1)
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#category-222 > .dropdown-item")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.LINK_TEXT, "Dyski SSD").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(1) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        self.driver.implicitly_wait(1)
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(2) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".touchspin-up").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary > .material-icons").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(3) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".bootstrap-touchspin-up").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(4) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(5) img").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(6) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".bootstrap-touchspin-down")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(7) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary > .material-icons").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(8) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".bootstrap-touchspin-down")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(9) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, "ol > li:nth-child(4) span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(10) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary > .material-icons").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header .hidden-sm-down").click()


