# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBSearchupaproductandaddarandomonefromthelot():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bSearchupaproductandaddarandomonefromthelot(self):
    self.driver.get("https://prestashop:8443/index.php")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.NAME, "s").click()
    self.driver.find_element(By.NAME, "s").send_keys("mysze")
    self.driver.find_element(By.NAME, "s").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(3) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    self.driver.close()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
  
