# Generated by Selenium IDE
import pytest
import time
import json
import random
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test:
    def setup_method(self):
        options = Options()
        options.add_experimental_option("detach", True)
        options.add_argument('--ignore-ssl-errors=yes')
        options.add_argument('--ignore-certificate-errors')
        options.add_argument('--allow-insecure-localhost')
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test(self):
        self.driver.get("https://prestashop:8443/index.php")
        self.driver.maximize_window()
        self.driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
        self.driver.find_element(By.LINK_TEXT, "Nie masz konta? Załóż je tutaj").click()
        self.driver.find_element(By.ID, "field-id_gender-1").click()
        self.driver.find_element(By.ID, "field-firstname").click()
        self.driver.find_element(By.ID, "field-firstname").send_keys("Jan")
        self.driver.find_element(By.ID, "field-lastname").send_keys("Kowalski")
        self.driver.find_element(By.ID, "field-email").send_keys(f"szybkipingwin.{random.randint(0, 10000)}@gmail.com")
        self.driver.find_element(By.ID, "field-password").send_keys("haslo123")
        self.driver.find_element(By.ID, "field-birthday").click()
        self.driver.find_element(By.ID, "field-birthday").send_keys("1970-05-31")
        self.driver.find_element(By.NAME, "optin").click()
        self.driver.find_element(By.NAME, "customer_privacy").click()
        self.driver.find_element(By.NAME, "newsletter").click()
        self.driver.find_element(By.NAME, "psgdpr").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-control-submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".account > .hidden-sm-down").click()
