# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDAccountregistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dAccountregistration(self):
    self.driver.get("https://prestashop:8443/index.php")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".user-info .hidden-sm-down").click()
    self.driver.find_element(By.LINK_TEXT, "Nie masz konta? Załóż je tutaj").click()
    self.driver.find_element(By.ID, "field-id_gender-1").click()
    self.driver.find_element(By.ID, "field-firstname").click()
    self.driver.find_element(By.ID, "field-firstname").send_keys("Jan")
    self.driver.find_element(By.ID, "field-lastname").click()
    self.driver.find_element(By.ID, "field-lastname").send_keys("Kowalski")
    self.driver.find_element(By.ID, "field-email").click()
    self.driver.find_element(By.ID, "field-email").send_keys("szybkipingwin.com")
    self.driver.find_element(By.ID, "field-password").click()
    self.driver.find_element(By.ID, "field-password").send_keys("hasło123")
    self.driver.find_element(By.ID, "field-birthday").click()
    self.driver.find_element(By.ID, "field-birthday").send_keys("1970-05-31")
    self.driver.find_element(By.ID, "main").click()
    self.driver.find_element(By.NAME, "optin").click()
    self.driver.find_element(By.NAME, "customer_privacy").click()
    self.driver.find_element(By.NAME, "newsletter").click()
    self.driver.find_element(By.NAME, "psgdpr").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control-submit").click()
    self.driver.find_element(By.ID, "field-email").send_keys("szybkipingwin@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control-submit").click()
  
